import { Sim } from '../shared/sim.js';
const sim = new Sim({ seed: 7, size: 96, eraId: 'antiquity', players: [ { name: 'H', faction: 'rome', team: 0, color: 0 }, { name: 'B', faction: 'gaul', team: 1, color: 1, isAI: true } ] });
const me = sim.players[0]; const s = me.spawn;
const a = { x: s.x - 6, y: s.y - 6 }, b = { x: s.x + 6, y: s.y - 6 };
while (!sim.buildable[a.y * sim.w + a.x]) a.x++; while (!sim.buildable[b.y * sim.w + b.x]) b.x--;
const path = sim.wallPath(a.x, a.y, b.x, b.y);
console.log(path.map(t => `${t.x},${t.y}:${sim.footprintFree(t.x, t.y, 1, 1) ? 'ok' : 'BLOCKED ' + (sim.ents.get(sim.blockId[t.y*sim.w+t.x])||{}).kind}`).join(' '));
const workers = [...sim.ents.values()].filter(e => e.kind === 'unit' && e.owner === 0).map(u => u.id);
sim.command(0, { t: 'wall', ids: workers.slice(0, 2), x0: a.x, y0: a.y, x1: b.x, y1: b.y });
console.log('walls', [...sim.ents.values()].filter(e => e.kind === 'building' && e.type === 'wall').length, 'events', JSON.stringify(sim.events));
